const { chromium } = require("playwright");

// Smoke test against the REAL Docker stack (nginx with self-signed cert).
// Run in CI after `docker compose up -d --build`. Depends on:
//   - port 80 -> 301 redirect to HTTPS (443)
//   - self-signed certificate generated by the frontend entrypoint
//   - CSP header present with `script-src 'self'` (no unsafe-inline)
//   - kiosk + admin still work over HTTPS

const HTTP = "http://localhost/";
const HTTPS = "https://localhost";
const executable = process.env.CHROMIUM_PATH || "/usr/bin/chromium";
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || "test-admin-password";

let failures = 0;
function check(ok, msg) {
  if (ok) {
    console.log("PASS  " + msg);
  } else {
    failures += 1;
    console.error("FAIL  " + msg);
  }
}

async function main() {
  const browser = await chromium.launch({
    executablePath: executable,
    args: ["--no-sandbox", "--disable-dev-shm-usage"],
  });
  const context = await browser.newContext({ ignoreHTTPSErrors: true });
  const page = await context.newPage();
  const errors = [];
  page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
  page.on("pageerror", (e) => errors.push("PAGEERROR: " + e.message));

  // 1. Health check over HTTPS through nginx.
  const health = await context.request.get(HTTPS + "/api/health");
  const healthJson = await health.json().catch(() => ({}));
  check(health.status() === 200 && healthJson.status === "ok", "backend health ok over https");

  // 2. CSP header present and inline scripts disabled.
  const root = await context.request.get(HTTPS + "/");
  const csp = root.headers()["content-security-policy"] || "";
  check(csp.length > 0, "Content-Security-Policy header present");
  const scriptSrc = (csp.match(/script-src\s+[^;]*/) || [""])[0];
  check(!/unsafe-inline|unsafe-eval/.test(scriptSrc), "script-src has no unsafe-inline/eval: " + scriptSrc);

  // 3. Plain HTTP redirects to HTTPS.
  const redirResp = await page.goto(HTTP, { waitUntil: "domcontentloaded" }).catch(() => null);
  const finalUrl = page.url();
  check(
    redirResp && redirResp.request().redirectedFrom() && finalUrl.startsWith("https://"),
    "http:// redirects to https (final URL " + finalUrl + ")"
  );

  // 4. Kiosk renders products over HTTPS (proves static files + /api proxy + scripts run).
  await page.goto(HTTPS + "/", { waitUntil: "networkidle" });
  await page.waitForSelector(".product-card", { timeout: 10000 }).catch(() => {});
  const productCards = await page.locator(".product-card").count();
  check(productCards > 0, "kiosk product cards rendered over https (" + productCards + ")");

  // 5. Admin login works over HTTPS with default admin credentials.
  await page.goto(HTTPS + "/#admin", { waitUntil: "networkidle" });
  const hasLogin = (await page.locator("#login-form").count()) > 0;
  check(hasLogin, "admin sign-in form present over https");
  if (hasLogin) {
    await page.fill("#login-username", "admin");
    await page.fill("#login-password", ADMIN_PASSWORD);
    await page.click("#login-form button[type=submit]");
    const loggedIn = await page.waitForSelector(".admin-layout", { timeout: 5000 }).then(() => true).catch(() => false);
    check(loggedIn, "admin login succeeds over https");
  }

  const pageErrors = errors.filter((m) => !m.includes("favicon"));
  check(pageErrors.length === 0, "no console/page errors" + (pageErrors.length ? ": " + pageErrors.join(" | ") : ""));

  await browser.close();
  process.exit(failures === 0 ? 0 : 1);
}

main().catch((e) => {
  console.error("SMOKE ERROR: " + e.message);
  process.exit(1);
});